apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: django
  name: django
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: benthomasson/insights_ansible_runner_poc_production_django
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
